// flow-typed signature: f4681e252e29a726f52b3e758557af42
// flow-typed version: <<STUB>>/jest-serializer-html-string_v^1.0.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-serializer-html-string'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-serializer-html-string' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'jest-serializer-html-string/index' {
  declare module.exports: $Exports<'jest-serializer-html-string'>;
}
declare module 'jest-serializer-html-string/index.js' {
  declare module.exports: $Exports<'jest-serializer-html-string'>;
}
