// flow-typed signature: a776f8f863112dcb394e2644e1ae1e67
// flow-typed version: <<STUB>>/preact-render-to-json_v^3.6.6/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'preact-render-to-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'preact-render-to-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'preact-render-to-json/dist/index' {
  declare module.exports: any;
}

declare module 'preact-render-to-json/rollup.config' {
  declare module.exports: any;
}

declare module 'preact-render-to-json/src/index' {
  declare module.exports: any;
}

declare module 'preact-render-to-json/src/util' {
  declare module.exports: any;
}

declare module 'preact-render-to-json/test/index' {
  declare module.exports: any;
}

declare module 'preact-render-to-json/test/render' {
  declare module.exports: any;
}

// Filename aliases
declare module 'preact-render-to-json/dist/index.js' {
  declare module.exports: $Exports<'preact-render-to-json/dist/index'>;
}
declare module 'preact-render-to-json/rollup.config.js' {
  declare module.exports: $Exports<'preact-render-to-json/rollup.config'>;
}
declare module 'preact-render-to-json/src/index.js' {
  declare module.exports: $Exports<'preact-render-to-json/src/index'>;
}
declare module 'preact-render-to-json/src/util.js' {
  declare module.exports: $Exports<'preact-render-to-json/src/util'>;
}
declare module 'preact-render-to-json/test/index.js' {
  declare module.exports: $Exports<'preact-render-to-json/test/index'>;
}
declare module 'preact-render-to-json/test/render.js' {
  declare module.exports: $Exports<'preact-render-to-json/test/render'>;
}
