// flow-typed signature: cd0af3b3053ffedb6cf9935985bcdf38
// flow-typed version: <<STUB>>/@storybook/addon-jest_v^3.2.16/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-jest/dist/colors' {
  declare module.exports: any;
}

declare module '@storybook/addon-jest/dist/components/Indicator' {
  declare module.exports: any;
}

declare module '@storybook/addon-jest/dist/components/Panel' {
  declare module.exports: any;
}

declare module '@storybook/addon-jest/dist/components/PanelTitle' {
  declare module.exports: any;
}

declare module '@storybook/addon-jest/dist/components/Result' {
  declare module.exports: any;
}

declare module '@storybook/addon-jest/dist/hoc/provideJestResult' {
  declare module.exports: any;
}

declare module '@storybook/addon-jest/dist/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-jest/dist/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-jest/dist/styles' {
  declare module.exports: any;
}

declare module '@storybook/addon-jest/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-jest/src/colors' {
  declare module.exports: any;
}

declare module '@storybook/addon-jest/src/components/Indicator' {
  declare module.exports: any;
}

declare module '@storybook/addon-jest/src/components/Panel' {
  declare module.exports: any;
}

declare module '@storybook/addon-jest/src/components/PanelTitle' {
  declare module.exports: any;
}

declare module '@storybook/addon-jest/src/components/Result' {
  declare module.exports: any;
}

declare module '@storybook/addon-jest/src/hoc/provideJestResult' {
  declare module.exports: any;
}

declare module '@storybook/addon-jest/src/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-jest/src/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-jest/src/styles' {
  declare module.exports: any;
}

declare module '@storybook/addon-jest/styles' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-jest/dist/colors.js' {
  declare module.exports: $Exports<'@storybook/addon-jest/dist/colors'>;
}
declare module '@storybook/addon-jest/dist/components/Indicator.js' {
  declare module.exports: $Exports<'@storybook/addon-jest/dist/components/Indicator'>;
}
declare module '@storybook/addon-jest/dist/components/Panel.js' {
  declare module.exports: $Exports<'@storybook/addon-jest/dist/components/Panel'>;
}
declare module '@storybook/addon-jest/dist/components/PanelTitle.js' {
  declare module.exports: $Exports<'@storybook/addon-jest/dist/components/PanelTitle'>;
}
declare module '@storybook/addon-jest/dist/components/Result.js' {
  declare module.exports: $Exports<'@storybook/addon-jest/dist/components/Result'>;
}
declare module '@storybook/addon-jest/dist/hoc/provideJestResult.js' {
  declare module.exports: $Exports<'@storybook/addon-jest/dist/hoc/provideJestResult'>;
}
declare module '@storybook/addon-jest/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-jest/dist/index'>;
}
declare module '@storybook/addon-jest/dist/register.js' {
  declare module.exports: $Exports<'@storybook/addon-jest/dist/register'>;
}
declare module '@storybook/addon-jest/dist/styles.js' {
  declare module.exports: $Exports<'@storybook/addon-jest/dist/styles'>;
}
declare module '@storybook/addon-jest/register.js' {
  declare module.exports: $Exports<'@storybook/addon-jest/register'>;
}
declare module '@storybook/addon-jest/src/colors.js' {
  declare module.exports: $Exports<'@storybook/addon-jest/src/colors'>;
}
declare module '@storybook/addon-jest/src/components/Indicator.js' {
  declare module.exports: $Exports<'@storybook/addon-jest/src/components/Indicator'>;
}
declare module '@storybook/addon-jest/src/components/Panel.js' {
  declare module.exports: $Exports<'@storybook/addon-jest/src/components/Panel'>;
}
declare module '@storybook/addon-jest/src/components/PanelTitle.js' {
  declare module.exports: $Exports<'@storybook/addon-jest/src/components/PanelTitle'>;
}
declare module '@storybook/addon-jest/src/components/Result.js' {
  declare module.exports: $Exports<'@storybook/addon-jest/src/components/Result'>;
}
declare module '@storybook/addon-jest/src/hoc/provideJestResult.js' {
  declare module.exports: $Exports<'@storybook/addon-jest/src/hoc/provideJestResult'>;
}
declare module '@storybook/addon-jest/src/index.js' {
  declare module.exports: $Exports<'@storybook/addon-jest/src/index'>;
}
declare module '@storybook/addon-jest/src/register.js' {
  declare module.exports: $Exports<'@storybook/addon-jest/src/register'>;
}
declare module '@storybook/addon-jest/src/styles.js' {
  declare module.exports: $Exports<'@storybook/addon-jest/src/styles'>;
}
declare module '@storybook/addon-jest/styles.js' {
  declare module.exports: $Exports<'@storybook/addon-jest/styles'>;
}
